name: Update Discord Card

on:
  schedule:
    # This runs the action every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch:

# This block gives the workflow permission to write to your repository
permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update card URL with current timestamp
        run: |
          # This command finds the discord image URL and replaces the number after ?v= with the current time
          sed -i "s|/api/discord?v=[0-9]*|/api/discord?v=$(date +%s)|" README.md

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: update discord card cache buster"
          file_pattern: README.md
