name: Update Discord Activity Card

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:    # Allows manual triggering

jobs:
  update-card:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests aiohttp Pillow fastapi uvicorn

      - name: Generate and download card
        run: |
          import requests
          import os
          url = "http://api.dtester.xyz:3003/v2/card/user/591534252307513347"
          response = requests.get(url, headers={"Cache-Control": "no-cache"})
          if response.status_code == 200:
              with open("discord_card.png", "wb") as f:
                  f.write(response.content)
          else:
              raise Exception(f"Failed to download card: {response.status_code}")

      - name: Commit and push if changed
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add discord_card.png
          git diff --quiet && git diff --staged --quiet || git commit -m "Update Discord activity card"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
